service: microservice-mercadolibre-products-aws

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 10
  environment: ${file(./serverless_ssm.yml)}
  apiGateway:
    apiKeys:
      - name: xApiKey
        value: ${file(./serverless_ssm.yml):X_API_KEY}
  logs:
    # Enable REST API logs
    restApi:
      accessLogging: true
      format: "requestId: $context.requestId"
      executionLogging: true
      level: INFO
      fullExecutionData: true
      role: arn:aws:iam::xxxx:role
      roleManagedExternally: false

plugins:
  - serverless-esbuild
  - serverless-plugin-typescript
  - serverless-offline-ssm
  - serverless-offline

functions:
 databaseTestConnection:
    handler: src/controllers/db/connection.handler
    description: Function in charge of checking the connection to the db
    events:
      - http:
          path: /db-connection
          method: get
          private: true
 
resources:
  - ${file(src/resources/api-gateway.yml)}

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
  serverless-offline-ssm:
    stages:
      - dev
    ssm: ${file(./serverless_ssm.yml)}